### ISSUE TITLE
CHEROb crashes on .xml project open

### ISSUE THREAD

**Issue by maria364** [WeiqiJust/CHER-Ob#1]
I have managed to compile your project, CHER-Ob, in Microsoft Visual Studio 2010 (os:Windows 8). 

The program crashes every time I try to open an .xml project with multiple images. It cannot open neither CHER-Ob examples (the .xml file) nor my saved projects. It happens only in projects with many images, or with .obj files with texture (color). 

I have linked all the libraries in compilation without any problem, but I have no idea which one might cause the problem. 

Could you please help me a little with this?  
Thank you in advance.

**Comment by zachzeyuwang** [comment]
It seems that the problem remains Qt XML library issues. If you didn't compile Qt XML and build dlls corresponding to your environment, the program may not know what to do for some function calls (opening XML files). Please first check whether you have Qt XML dll and let us know if there is any further problems.

We recommend you use Visual Studio 2008 to compile the latest CHER-Ob, because all the libraries and dependencies you can find on GitHub is built based on this environment. Otherwise you may have to build them (including Qt, VTK, ITK, etc.) manually from source codes. Please refer to detailed instructions on https://github.com/WeiqiJust/CHER-Ob.

**Comment by maria364** [comment]
The problem was the format of the file which I was trying to open. The wrong format was .obj file with texture, but it seems that the program cannot handle such king of information on project opening (.xml file). Now that I have changed the format of the file (.ply file with texture), both the compiled and the downloaded program work fine without any crash. 

Thank you for your help.

**Comment by zachzeyuwang** [comment]
We did detect crashes if material and texture files are missing for .obj format. We have made modifications to copy all the corresponding files when .obj is imported and double check if there is anything missing when opening projects. You may find the latest codes shortly.
